// Auto-generated by Supabase CLI — do not edit manually.
// Run: npx supabase gen types typescript --project-id <YOUR_PROJECT_ID> > app/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      mysteries: {
        Row: {
          id: string;
          slug: string;
          title: string;
          summary: string;
          description: string;
          status: "published" | "draft" | "archived";
          classification_level: "disturbing" | "extreme" | "classified";
          image_url: string | null;
          latitude: number | null;
          longitude: number | null;
          year_occurred: number | null;
          views_count: number;
          rating_avg: number;
          rating_count: number;
          category_id: string;
          country_id: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          created_by: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["mysteries"]["Row"],
          | "id"
          | "created_at"
          | "updated_at"
          | "views_count"
          | "rating_avg"
          | "rating_count"
        >;
        Update: Partial<Database["public"]["Tables"]["mysteries"]["Insert"]>;
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          color: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["categories"]["Row"],
          "id" | "created_at"
        >;
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
      };
      profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          role: "visitor" | "reader" | "editor" | "admin";
          reputation_points: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["profiles"]["Row"],
          "created_at" | "updated_at" | "reputation_points"
        >;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      comments: {
        Row: {
          id: string;
          user_id: string;
          mystery_id: string;
          content: string;
          status: "pending" | "approved" | "spam";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["comments"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["comments"]["Insert"]>;
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          mystery_id: string;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["favorites"]["Row"],
          "id" | "created_at"
        >;
        Update: never;
      };
      ratings: {
        Row: {
          id: string;
          user_id: string;
          mystery_id: string;
          score: number;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["ratings"]["Row"],
          "id" | "created_at"
        >;
        Update: Pick<Database["public"]["Tables"]["ratings"]["Row"], "score">;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
